conn = database('','root','Fairbanks1!','com.mysql.jdbc.Driver', ...
	'jdbc:mysql://fairbanks.amath.washington.edu:3306/spanky_db');

TEMCBC = fetch(exec(conn, ['SELECT fBC.analyses_id, fMC.`nev file`, fMC.unit tounit, '...
' egMC.fromunit, egMC.score egMCscore, egBC.score egBCscore FROM `experiment_tuning` et '...
'INNER JOIN `fits` fMC '...
'ON et.`manualrecording` = fMC.`nev file` '...
'INNER JOIN `estimates_te` egMC '...
'ON egMC.`id` = fMC.`id` '...
'INNER JOIN `fits` fBC '...
'ON et.`1DBCrecording` = fBC.`nev file` '...
'INNER JOIN `estimates_te` egBC '...
'ON egBC.`id` = fBC.`id` '...
'WHERE fMC.unit = fBC.unit AND egMC.fromunit = egBC.fromunit AND fMC.modelID = 37 AND fBC.modelID = 37 AND fMC.analyses_id = fBC.analyses_id']));
TEMC = cell2mat(TEMCBC.Data(:,5));
TEBC = cell2mat(TEMCBC.Data(:,6));


TEMCMC2 = fetch(exec(conn, ['SELECT fBC.analyses_id, fMC.`nev file`, fMC.unit tounit, '...
' egMC.fromunit, egMC.score egMCscore, egBC.score egBCscore FROM `experiment_tuning` et '...
'INNER JOIN `fits` fMC '...
'ON et.`manualrecording` = fMC.`nev file` '...
'INNER JOIN `estimates_te` egMC '...
'ON egMC.`id` = fMC.`id` '...
'INNER JOIN `fits` fBC '...
'ON et.`manualrecordingafter` = fBC.`nev file` '...
'INNER JOIN `estimates_te` egBC '...
'ON egBC.`id` = fBC.`id` '...
'WHERE fMC.unit = fBC.unit AND egMC.fromunit = egBC.fromunit AND fMC.modelID = 37 AND fBC.modelID = 37 AND fMC.analyses_id = fBC.analyses_id']));
TEMCb = cell2mat(TEMCMC2.Data(:,5));
TEMC2 = cell2mat(TEMCMC2.Data(:,6));


TEBCDC = fetch(exec(conn, ['SELECT fBC.analyses_id, fMC.`nev file`, fMC.unit tounit, '...
' egMC.fromunit, egMC.score egMCscore, egBC.score egBCscore FROM `experiment_tuning` et '...
'INNER JOIN `fits` fMC '...
'ON et.`1DBCrecording` = fMC.`nev file` '...
'INNER JOIN `estimates_te` egMC '...
'ON egMC.`id` = fMC.`id` '...
'INNER JOIN `fits` fBC '...
'ON et.`dualrecording` = fBC.`nev file` '...
'INNER JOIN `estimates_te` egBC '...
'ON egBC.`id` = fBC.`id` '...
'WHERE fMC.unit = fBC.unit AND egMC.fromunit = egBC.fromunit AND fMC.modelID = 37 AND fBC.modelID = 37 AND fMC.analyses_id = fBC.analyses_id']));
TEBCb = cell2mat(TEBCDC.Data(:,5));
TEDC = cell2mat(TEBCDC.Data(:,6));

C1=corr(TEMC, TEBC);
%corr(TEMCb, TEMC2);
TEMCc=TEMC;
C2=corr(TEMC, TEDC);
C3=corr(TEBCb, TEDC);

%%

%For individual recordings
mcrec = fetch(exec(conn, ['SELECT et.`manualrecording`, et.`1DBCrecording` FROM experiment_tuning et']));
mcrec = mcrec.Data;
nR = size(mcrec,1);

corrsMCBC = [];
corrsMCMC2 = [];
corrsMCDC = [];
corrsBCDC = [];

for idx = 1:nR
	mcfile = mcrec{idx,1};
	bcfile = mcrec{idx,2};
	TEMCBC = fetch(exec(conn, ['SELECT fBC.analyses_id, fMC.`nev file`, fMC.unit tounit, '...
	' egMC.fromunit, egMC.score egMCscore, egBC.score egBCscore FROM `experiment_tuning` et '...
	'INNER JOIN `fits` fMC '...
	'ON et.`manualrecording` = fMC.`nev file` '...
	'INNER JOIN `estimates_te` egMC '...
	'ON egMC.`id` = fMC.`id` '...
	'INNER JOIN `fits` fBC '...
	'ON et.`1DBCrecording` = fBC.`nev file` '...
	'INNER JOIN `estimates_te` egBC '...
	'ON egBC.`id` = fBC.`id` '...
	'WHERE fMC.unit = fBC.unit AND egMC.fromunit = egBC.fromunit AND fMC.modelID = 37 AND fBC.modelID = 37 AND fMC.analyses_id = fBC.analyses_id AND fMC.`nev file` = "' mcfile '"']));
	if length(TEMCBC.Data) > 1
		TEMC = cell2mat(TEMCBC.Data(:,5));
		TEBC = cell2mat(TEMCBC.Data(:,6));
		corrsMCBC(idx) = corr(TEMC, TEBC);
    end

    % 	TEMCMC2 = fetch(exec(conn, ['SELECT fBC.analyses_id, fMC.`nev file`, fMC.unit tounit, '...
% 	' egMC.fromunit, egMC.score egMCscore, egBC.score egBCscore FROM `experiment_tuning` et '...
% 	'INNER JOIN `fits` fMC '...
% 	'ON et.`manualrecording` = fMC.`nev file` '...
% 	'INNER JOIN `estimates_te` egMC '...
% 	'ON egMC.`id` = fMC.`id` '...
% 	'INNER JOIN `fits` fBC '...
% 	'ON et.`manualrecordingafter` = fBC.`nev file` '...
% 	'INNER JOIN `estimates_te` egBC '...
% 	'ON egBC.`id` = fBC.`id` '...
% 	'WHERE fMC.unit = fBC.unit AND egMC.fromunit = egBC.fromunit AND fMC.modelID = 37 AND fBC.modelID = 37 AND fMC.analyses_id = fBC.analyses_id AND fMC.`nev file` = "' mcfile '"']));
% 	if length(TEMCMC2.Data) > 1
% 		TEMCb = cell2mat(TEMCMC2.Data(:,5));
% 		TEMC2 = cell2mat(TEMCMC2.Data(:,6));
% 		corrsMCMC2(idx) = corr(TEMCb, TEMC2);
% 	end
	
	TEMCDC = fetch(exec(conn, ['SELECT fBC.analyses_id, fMC.`nev file`, fMC.unit tounit, '...
	' egMC.fromunit, egMC.score egMCscore, egBC.score egBCscore FROM `experiment_tuning` et '...
	'INNER JOIN `fits` fMC '...
	'ON et.`manualrecording` = fMC.`nev file` '...
	'INNER JOIN `estimates_te` egMC '...
	'ON egMC.`id` = fMC.`id` '...
	'INNER JOIN `fits` fBC '...
	'ON et.`dualrecording` = fBC.`nev file` '...
	'INNER JOIN `estimates_te` egBC '...
	'ON egBC.`id` = fBC.`id` '...
	'WHERE fMC.unit = fBC.unit AND egMC.fromunit = egBC.fromunit AND fMC.modelID = 37 AND fBC.modelID = 37 AND fMC.analyses_id = fBC.analyses_id AND fMC.`nev file` = "' mcfile '"']));
	if length(TEMCDC.Data) > 1
		TEMCc = cell2mat(TEMCDC.Data(:,5));
		TEDC = cell2mat(TEMCDC.Data(:,6));
		corrsMCDC(idx) = corr(TEMCc, TEDC);
	end
	TEBCDC = fetch(exec(conn, ['SELECT fBC.analyses_id, fMC.`nev file`, fMC.unit tounit, '...
	' egMC.fromunit, egMC.score egMCscore, egBC.score egBCscore FROM `experiment_tuning` et '...
	'INNER JOIN `fits` fMC '...
	'ON et.`1DBCrecording` = fMC.`nev file` '...
	'INNER JOIN `estimates_te` egMC '...
	'ON egMC.`id` = fMC.`id` '...
	'INNER JOIN `fits` fBC '...
	'ON et.`dualrecording` = fBC.`nev file` '...
	'INNER JOIN `estimates_te` egBC '...
	'ON egBC.`id` = fBC.`id` '...
	'WHERE fMC.unit = fBC.unit AND egMC.fromunit = egBC.fromunit AND fMC.modelID = 37 AND fBC.modelID = 37 AND fMC.analyses_id = fBC.analyses_id AND fMC.`nev file` = "' bcfile '"']));
	if length(TEBCDC.Data) > 1
		TEBCb = cell2mat(TEBCDC.Data(:,5));
		TEDC = cell2mat(TEBCDC.Data(:,6));
		corrsBCDC(idx) = corr(TEBCb, TEDC);
	end
end

